---
elasticsearch:
  hosts:
    el-instance:
      ansible_host: 10.0.2.7
kibana:
  hosts:
    kib-instance:
      ansible_host: 10.0.2.15
filebeat:
  hosts:
    file-instance:
      ansible_host: 10.0.2.9